name: Hitlist Tracker

on: fork

permissions: write-all

jobs:
  updateTracker:
    name: Update Hitlist Tracker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Update Hitlist File
        uses: actions/github-script@v8
        with:
          script: |
            import fs from node:fs;

            const forks = github.rest.repos.listForks({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            if (forks.length < 1) {
              console.log("No forks exist for the repository");
              process.exit(0);
              return;
            }

            // i have no idea how github organizes the forks
            // whether its by date, alphabetically, or whatever
            // this checks for the most recent fork

            // default to the repo's creation date
            const mostRecentDate = new Date(github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            }).created_at);

            for (const fork in forks) {
              const forkDate = new Date(fork.created_at);
              if (forkDate.getTime() > mostRecentDate.getTime()) {
                mostRecentDate = forkDate;
              }
            }

            // default to the first fork in the list
            const mostRecentFork = forks[0];

            for (const fork in forks) {
              const forkDate = new Date(fork.created_at);
              if (forkDate.getTime() == mostRecentDate.getTime()) {
                mostRecentFork = fork;
              }
            }

            const hitlistRawFile = fs.readFileSync("hitlist.md", "utf8");

            // dox the guy that forked the repo muahaahahahah
            hitlistRawFile += "\n";
            hitlistRawFile += mostRecentFork.owner.login + "\n";
            hitlistRawFile += mostRecentFork.html_url + "\n";
            hitlistRawFile += mostRecentDate.toLocaleDateString("en-US", {month: "long", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit"}) + "\n";

            const latestRef = github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/main",
            });

            const latestCommit = github.rest.git.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: latestRef.object.sha
            });

            const hitlistBlob = github.rest.git.createBlob({
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: hitlistRawFile,
              encoding: "utf-8"
            });

            const newTree = github.rest.git.createTree({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base_tree: latestCommit.tree.sha,
              tree: [{
                path: "hitlist.md",
                mode: "100644", // this number means: https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#:~:text=In%20this%20case%2C%20you%E2%80%99re%20specifying%20a%20mode%20of%20100644%2C%20which%20means%20it%E2%80%99s%20a%20normal%20file.
                type: "blob",
                sha: hitlistBlob.sha
              }],
            });

            const newCommit = github.rest.git.createCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tree: newTree.sha,
              message: "Updated Hitlist Tracker file",
              parents: [latestRef.object.sha]
            });

            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/main",
              sha: newCommit.sha
            });
