name: Build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - assets/**
      - setup/CheckHXCPP.hx
      - setup/setup-windows.bat
      - setup/setup.sh
      - source/**
      - project.hxp

permissions: write-all

jobs:
  buildLinux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v6

      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/

      - name: Install LibVLC and Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          chmod +x ./setup/setup.sh
          sh ./setup/setup.sh
          haxe -cp setup -D analyzer-optimize --run CheckHXCPP

      - name: Build Game
        run: |
          haxelib run lime build linux

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (Linux)
          path: export/release/linux/bin

      - name: Clear Old Cache
        uses: actions/github-script@v8
        if: ${{ steps.cache-restore.outputs.cache-hit == 'true' }}
        with:
          script: |
            await github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_linux"
            });

      - name: Save New Cache
        uses: actions/cache/save@v5
        with:
          key: cache_linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/

  buildWindows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v6

      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/

      - name: Install Libraries
        run: |
          .\"setup/setup-windows.bat"
          haxe -cp setup -D analyzer-optimize --run CheckHXCPP
        shell: cmd

      - name: Build Game
        run: haxelib run lime build windows

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (Windows)
          path: export/release/windows/bin

      - name: Clear Old Cache
        uses: actions/github-script@v8
        if: ${{ steps.cache-restore.outputs.cache-hit == 'true' }}
        with:
          script: |
            await github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_windows"
            });

      - name: Save New Cache
        uses: actions/cache/save@v5
        with:
          key: cache_windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/

  buildMac:
    name: MacOS Build
    runs-on: macos-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v6

      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/

      - name: Install Libraries
        run: |
          chmod +x ./setup/setup.sh
          sh ./setup/setup.sh
          haxe -cp setup -D analyzer-optimize --run CheckHXCPP

      - name: Build Game
        run: arch -x86_64 haxelib run lime build mac

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (MacOS)
          path: export/release/macos/bin

      - name: Clear Old Cache
        uses: actions/github-script@v8
        if: ${{ steps.cache-restore.outputs.cache-hit == 'true' }}
        with:
          script: |
            await github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_mac"
            });

      - name: Save New Cache
        uses: actions/cache/save@v5
        with:
          key: cache_mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/

  buildAndroid:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v6

      - name: Install Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Install Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Install Android NDK
        id: ndk-install
        uses: nttld/setup-ndk@v1.6.0
        with:
          ndk-version: r29

      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          key: cache_android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/

      - name: Install Libraries
        run: |
          chmod +x ./setup/setup.sh
          sh ./setup/setup.sh
          haxe -cp setup -D analyzer-optimize --run CheckHXCPP

      - name: Set up Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.ndk-install.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME ${{ env.JAVA_HOME }}
          haxelib run lime config ANDROID_SETUP true

      - name: Build Game
        run: haxelib run lime build android

      - name: Build APK
        run: |
          chmod +x export/release/android/bin/gradlew

          cd export/release/android/bin/
          ./gradlew clean
          ./gradlew assembleDebug
          cd ../../../../

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (Android)
          path: export/release/android/bin/app/build/outputs/apk/debug

      - name: Clear old Cache
        uses: actions/github-script@v8
        if: ${{ steps.cache-restore.outputs.cache-hit == 'true' }}
        with:
          script: |
            await github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "cache_android"
            });

      - name: Save new Cache
        uses: actions/cache/save@v5
        with:
          key: cache_android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
