name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  buildLinux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v5
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Install LibVLC, Haxelib and Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp master
          chmod +x ./setup/setup.sh
          sh ./setup/setup.sh
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Set Up HXCPP
        run: |
          haxe ~/haxelib/hxcpp/git/tools/hxcpp/compile.hxml
      - name: Build Game
        run: |
          haxelib run lime build linux
      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (Linux)
          path: 'export/release/linux/bin'

  buildWindows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v5
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Install Haxelib and Libraries
        run: |
          haxelib setup C:/haxelib
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp master
          .\"setup/setup-windows.bat"
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Set Up HXCPP
        run: |
          haxe C:/haxelib/hxcpp/git/tools/hxcpp/compile.hxml
      - name: Build Game
        run: haxelib run lime build windows
      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (Windows)
          path: export/release/windows/bin

  buildMac:
    name: MacOS Build
    runs-on: macos-latest
    steps:
      - name: Pulling new Commit
        uses: actions/checkout@v5
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Install Haxelib and Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp master
          chmod +x ./setup/setup.sh
          sh ./setup/setup.sh
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Set Up HXCPP
        run: |
          haxe ~/haxelib/hxcpp/git/tools/hxcpp/compile.hxml
      - name: Build Game
        run: arch -x86_64 haxelib run lime build mac
      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Impostor Lite (MacOS)
          path: export/release/macos/bin
